#!/usr/bin/env node
// generate-sitemap.js
// Generates sitemap.xml from all active Supabase listings.
// Usage: node generate-sitemap.js > sitemap.xml
// Run after deploys or on a cron (e.g. daily).

const SUPABASE_URL  = 'https://gpodsuuugvwzldhfsrbv.supabase.co/rest/v1';
const SUPABASE_ANON = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imdwb2RzdXV1Z3Z3emxkaGZzcmJ2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzY5MjM3MjUsImV4cCI6MjA5MjQ5OTcyNX0.GrRyrh6BQNwGgHJAUaRRmsPS-jkhzXvACU9N9gih5LY';

async function fetchAllListings() {
  const res = await fetch(`${SUPABASE_URL}/inserate?select=id,titel,strasse,hausnummer,plz,ort,erstellt_am,aktualisiert_am&status=eq.aktiv&order=erstellt_am.desc`, {
    headers: {
      'apikey': SUPABASE_ANON,
      'Authorization': `Bearer ${SUPABASE_ANON}`,
      'Accept': 'application/json',
    }
  });
  if (!res.ok) throw new Error(`Supabase error: ${res.status}`);
  return res.json();
}

function slugify(str) {
  return str.toLowerCase()
    .replace(/ä/g,'ae').replace(/ö/g,'oe').replace(/ü/g,'ue').replace(/ß/g,'ss')
    .replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'');
}

async function main() {
  const listings = await fetchAllListings();

  const staticPages = [
    { loc: 'https://imomap.at/', changefreq: 'daily', priority: '1.0' },
  ];

  const listingEntries = listings.map(l => {
    const lastmod = (l.aktualisiert_am || l.erstellt_am || '').split('T')[0];
    const addr = [l.strasse, l.hausnummer, l.plz, l.ort].filter(Boolean).join(' ');
    const slug = slugify(`${l.titel || ''}-${addr}`);
    return `  <url>
    <loc>https://imomap.at/inserat/${slug}-${l.id}</loc>${lastmod ? `\n    <lastmod>${lastmod}</lastmod>` : ''}
    <changefreq>weekly</changefreq>
    <priority>0.8</priority>
  </url>`;
  });

  const staticEntries = staticPages.map(p => `  <url>
    <loc>${p.loc}</loc>
    <changefreq>${p.changefreq}</changefreq>
    <priority>${p.priority}</priority>
  </url>`);

  // Landing pages (generated by generate-landing-pages.js)
  let landingEntries = [];
  try {
    const fs = require('fs');
    const pages = JSON.parse(fs.readFileSync('landing-pages.json', 'utf8'));
    landingEntries = pages.map(p => `  <url>
    <loc>https://imomap.at${p}</loc>
    <changefreq>weekly</changefreq>
    <priority>0.9</priority>
  </url>`);
  } catch(e) {
    process.stderr.write('Hinweis: landing-pages.json nicht gefunden, Landing Pages nicht in Sitemap\n');
  }

  const xml = `<?xml version="1.0" encoding="UTF-8"?>
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
${[...staticEntries, ...landingEntries, ...listingEntries].join('\n')}
</urlset>`;

  process.stdout.write(xml + '\n');
  process.stderr.write(`✓ Sitemap generiert: ${listings.length} Inserate + ${staticPages.length} statische Seiten\n`);
}

main().catch(e => { process.stderr.write('Fehler: ' + e.message + '\n'); process.exit(1); });
